name: hoover_driver
description: A new Flutter project.


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.0
  firebase_core: ^0.5.3
  firebase_auth: ^0.18.4+1
  firebase_database: ^4.4.0
  connectivity: ^2.0.2
  google_maps_flutter: ^1.0.6
  outline_material_icons: ^0.1.1
  http: ^0.12.2
  geolocator: ^6.1.13
  provider: ^4.3.2+3
  flutter_polyline_points: ^0.2.4
  font_awesome_flutter: ^8.11.0
  animated_text_kit: ^3.1.0
  flutter_geofire: ^1.0.3
  firebase_messaging: ^7.0.3
  assets_audio_player: ^2.0.13+1
  toast: ^0.1.5
  maps_toolkit: ^1.1.0+2
  


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:


  uses-material-design: true

  
  assets:
    - images/
    - sounds/

  fonts:
    - family: Brand-Bold
      fonts:
        - asset: fonts/bolt-semibold.ttf
    - family: Brand-Regular
      fonts:
        - asset: fonts/bolt-regular.ttf
